### ISSUE TITLE
there is no processer.py present in the data

### ISSUE THREAD

**Issue by viru12** [niloxx/neuralPlateRecognition#1]
no processer.py present in the data

**Comment by gabriel-cf** [comment]
Thanks for noticing it, I must have renamed it at some point to `main.py`. I will update the README.

Try using from the `src\` directory: `python main.py ..\testing_full_system\testing_full_system`

Note: I haven't tested it for Linux but it should work

**Comment by gabriel-cf** [comment]
Updated the README pointing to `main.py`. Thank you

**Comment by viru12** [comment]
Ok thank you Gabriel for your positive response
